---
title: "Schedule"
---

*Please note: This is a preliminary schedule and will be updated prior to the course. Lecture slides will be made available before or during the course.*

## Day 1 (October 6, 2026)

| Time      	| Topic                                                                                                         	| Teacher                          	|
|-------------	|---------------------------------------------------------------------------------------------------------------	|--------------------------------	|
| 09:00-09:15 	| Welcome and [course introduction](presentations/SCO_course_intro.pdf)                                                                                	| Jennifer Fransson (NBIS, SE)        	|
| 09:15-10:00 	| Lecture: [Overview of SRT technologies](presentations/technology_overview.pdf)                                         	| Åsa Björklund (NBIS, SE)              |
| 10:00-10:15 	| Break                                                                                                         	|                                	|
| 10:15-11:00 	| Lecture: [Cell segmentation](presentations/cell_segmentation.pdf) and [Data Formats](presentations/data_formats.pdf)                                                     	| Christophe Avenel, Jonas Windhager (NBIS, SE)          |
| 11:00-11:10 	| Intro to practicals  | Aditya Singh (NBIS, SE)            |
| 11:10-11:45 	| Practical 0: [SRT data formats](practicals/html/Practical0_DataFormats.html)   | Jonas Windhager (NBIS, SE)            |
| 11:45-12:45 	| Lunch                                                                                                         	|                                	|
| 12:45-14:15 	| Practical 1: [Cell segmentation](practicals/html/Practical1_Segmentation_Cellpose.html)  | Suganya Sivagurunathan (NBIS, SE) |
| 14:15-15:00 	| Lecture: [Imaging-based spatial data analysis (preprocessing, QC and normalization)](presentations/imaging_based_analysis.pdf)   | Christophe Avenel (NBIS, SE) |
| 15:00-15:15 	| Break                                                                                                         	|                                	|
| 15:15-16:45 	| Practical 2: [Imaging-based analysis and QC](practicals/html/p2_imaging_based_data_analysis.html)  | Åsa Björklund (NBIS, SE) |
| 17:30- | Course Dinner  |  |
: {tbl-colwidths="[25,50,25]"}

## Day 2 (October 7, 2026)

| Time      	| Topic                                                                                             	    | Teacher               	|
|-------------	|---------------------------------------------------------------------------------------------------------  |--------------------------	|
| 09:00-09:45 	| Lecture: [Cell segmentation free analysis of SRT data](presentations/segmentation_free_analysis.pdf)          	    | Naveed Ishaque (BIH, DE) 	|
| 09:45-11:15 	| Practical 3: [Cell segmentation free analysis of SRT data](practicals/html/p3_segmentation_sainsc.html) | Aditya Singh (NBIS, SE) & Lucie Pfeiferova (CAS, CZ) |
| 11:15-12:00 	| Lecture: [Sequence-based data analysis (preprocessing, data structures, QC and normalization)](presentations/sequencing_based_analysis.pdf)    	| Åsa Björklund (NBIS, SE) |
| 12:00-13:00 	| Lunch                                                                                              	    |                          	|
| 13:00-14:30 	| Practical 4: [Sequence-based data analysis](practicals/html/p4-Sequence-based_Data_Analysis.html)        	| Åsa Björklund (NBIS, SE), Leslie Solorzano (NBIS, SE) |
| 14:30-14:45 	| Break                                                                                              	    |                           |
| 14:45-15:30 	| Lecture: [Spatial and single cell data integration](presentations/sc_integration.pdf)                         	    | Ahmed Mahfouz (LUMC, NL)  |
| 15:30-17:00 	| Practical 5: [Spatial and single cell data integration](practicals/html/p5_integration_sc.html)   	| Benedetta Manzato (LUMC, NL), Emma Vonk (LUMC, NL) |
: {tbl-colwidths="[25,50,25]"}

## Day 3 (October 8, 2026)

| Time      	| Topic                                                     	| Teacher                           	|
|-------------	|-------------------------------------------------------------	|------------------------------------	|
| 09:00-09:45 	| Lecture: [Multi-slice spatial data integration](presentations/multislice_integration.pdf)      | Benedetta Manzato (LUMC, NL) |
| 09:45-11:15 	| Practical 6: Multi-slice spatial data integration [Part A](practicals/html/p6_alignment_moscot.html) & [Part B](practicals/html/p6_alignment.html)   | Benedetta Manzato (LUMC, NL), Emma Vonk (LUMC, NL) |
| 11:15-12:00 	| Lecture: [Spatial statistics](presentations/spatial_stats.pdf)     	| Peiying Cai (UZH/SIB, CH)	                                |
| 12:00-13:00   | Lunch                                                         |                                       |
| 13:00-14:30 	| Practical 7: Spatial statistics [Part A](practicals/html/Practical7-01-point-pattern-analysis-vignette-solution.html) & [Part B](practicals/html/Practical7-02-lattice-data-analysis-vignette-solution.html)   | Peiying Cai (UZH/SIB, CH), Jennifer Fransson (NBIS, SE) |
| 14:30-14:45 	| Break                                                       	|                                    	|
| 14:45-15:30 	| Lecture: [Spatially aware clustering](presentations/spatially_aware_clustering.pdf)   	| Ahmed Mahfouz (LUMC, NL)         	|
| 15:30-16:15 	| Practical 8: [Domain identification and niche reconstruction](practicals/html/p8_niche_domain.html) 	| Benedetta Manzato (LUMC, NL), Emma Vonk (LUMC, NL)        	|
| 16:15-17:00 	| Guest lecture: From tissue biogeographies to spatial interactomes |  Stefania Giacomello, SciLifeLab / KTH  |
: {tbl-colwidths="[25,50,25]"}

## Day 4 (October 9, 2026)

| Time      	| Topic                                                 	| Teacher                      	|
|-------------	|---------------------------------------------------------	|------------------------------ |
| 09:00-09:45 	| Practical 8 continued: [Domain identification and niche reconstruction](practicals/html/p8_niche_domain.html) 	| Benedetta Manzato (LUMC, NL), Emma Vonk (LUMC, NL)        	|
| 09:45-10:30 	| Lecture: [Cell-cell communication](presentations/cc_communication.pdf) | Francesca Drummer (Helmholtz, DE) |
| 10:30-12:00 	| Practical 9: Cell-cell communication [Part A](practicals/html/html_CCC_LIANA.html) & [Part B](practicals/html/html_CCC_TensorCell2Cell.html)	| Francesca Drummer (Helmholtz, DE), Leslie Solorzano (NBIS, SE) |
| 12:00-13:00 	| Lunch and departure                                     	|                              	|
: {tbl-colwidths="[25,50,25]"}
