---
title: "Travel information"
---



# Course location 

* Uppsala Biomedical Centre (BMC), Uppsala University, Husargatan 3, Uppsala
* Room: Trippelrummet (E10:1307-1309), BMC (enter via C11)
* To find the room within BMC see [https://link.mazemap.com/DcIYaHIo]


## Transport options to BMC from Uppsala Central station

### Walk

BMC is located approximately 2.5 km from Uppsala Central Station. A walk takes around 30 min.  

### Bus 

The closest bus stop is "Uppsala Science Park". To travel by bus in Uppsala see [the UL website](https://www.ul.se/en) or the [UL app](https://www.ul.se/en/tickets/how-to-buy-a-ticket/the-UL-app/). The bus lines 3, 4, 8 and 11 all stop at Uppsala Central Station and Uppsala Science Park. 

# Accommodation

Unfortunately we do not have enough resources to help with hotel bookings. Uppsala town centre is approximately 2 km from BMC, so any hotel in that region could be a good choice. Some examples of hotels are provided below, ordered by proximity to BMC.

* [Hotel von Kraemer](https://hotelvonkraemer.se/) (900 m)
* [Akademihotellet](https://akademihotellet.se/en/) (1.7 km)
* [Best Western Uppsala](https://bestwesternuppsala.se) (1.9 km)
* [Grand Hotel Hörnan](https://www.grandhotellhornan.com/) (1.9 km)
* [Elite Hotel Academia](https://www.elite.se/hotell/uppsala/elite-hotel-academia-uppsala/) (2.1 km)
* [Best Western Hotel Svava](https://www.hotelsvava.se/) (2.2 km)
* [Scandic Uplandia](https://www.scandichotels.com/sv/hotell/scandic-uplandia) (2.4 km)
* [Clarion Hotel Gillet](https://www.strawberry.se/hotell/sverige/uppsala/clarion-hotel-gillet/) (2.4 km)



